<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thread Name_h-10 p-10px darkbg-bgTert_95d095</name>
   <tag></tag>
   <elementGuidId>bfee8848-68e3-4e5c-803d-356816c66c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8de81f0-1ef0-447b-be8a-473fc300dd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61f0bce4-81df-427f-b3e2-c460ec082c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Thread Name</value>
      <webElementGuid>ccd22428-e757-4103-873d-0367d09c6da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 p-[10px] dark:bg-bgTertiary bg-white dark:text-white text-colorTextLightMode text-base outline-none rounded-md placeholder:text-sm</value>
      <webElementGuid>90a0c38b-11e9-427b-bacd-5168239d968a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>aff0acc8-374e-4d17-a34e-768925c2e6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-row flex-1 bg-transparent&quot;]/div[@class=&quot;w-[480px] dark:bg-bgPrimary bg-bgLightModeSecond rounded-l-lg&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex flex-col flex-1 justify-end&quot;]/div[@class=&quot;flex-shrink-0 flex flex-col pb-4 px-4 dark:bg-bgPrimary bg-bgLightModeSecond h-auto relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex flex-col overflow-y-auto h-heightMessageViewChatThread&quot;]/div[@class=&quot;flex flex-col justify-end flex-grow&quot;]/div[@class=&quot;flex flex-col mt-4 mb-4&quot;]/input[@class=&quot;h-10 p-[10px] dark:bg-bgTertiary bg-white dark:text-white text-colorTextLightMode text-base outline-none rounded-md placeholder:text-sm&quot;]</value>
      <webElementGuid>18e8d81d-13bc-450e-854b-cfba4a5d09e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>c808a424-f754-472b-b277-e47545deadf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[4]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b6084304-b4ea-4981-8826-b427152e85ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b85bfaa6-7453-4dab-accf-73b30c9142da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter Thread Name']</value>
      <webElementGuid>dfe3165b-b381-4335-81fa-59c56884694e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
