<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_hi</name>
   <tag></tag>
   <elementGuidId>d76def54-d0a2-4e79-b9cc-079adf6b3208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='editorReactMention'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7b5a17a6-5fe0-4168-8124-1edd2629c553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>4b1ac4e6-8c6d-4f27-87b2-eaeb0aa29ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughs here...</value>
      <webElementGuid>7008fa11-ffb4-468e-a5e5-cd4b5ff1e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>2f6f0f04-6c23-4a87-9df6-ef99c7485cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hi</value>
      <webElementGuid>0ebc13de-7f99-4c93-936a-3730b0d041a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-row flex-1 bg-transparent&quot;]/div[@class=&quot;w-[480px] dark:bg-bgPrimary bg-bgLightModeSecond rounded-l-lg&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex flex-col flex-1 justify-end&quot;]/div[@class=&quot;flex-shrink-0 flex flex-col pb-4 px-4 dark:bg-bgPrimary bg-bgLightModeSecond h-auto relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;dark:bg-channelTextarea bg-channelTextareaLight dark:text-white text-colorTextLightMode rounded-md darkMode dark:bg-channelTextarea--multiLine&quot;]/div[@class=&quot;dark:bg-channelTextarea__control&quot;]/textarea[@id=&quot;editorReactMention&quot;]</value>
      <webElementGuid>6f9e742f-872d-425e-9519-4736230a8cd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='editorReactMention'])[2]</value>
      <webElementGuid>adf15153-5cbf-49a7-8f36-9b0abb6a9a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[4]/div/div[2]/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>8f8935cd-e7ca-4fd3-a185-139686c34255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hi'])[1]/following::textarea[1]</value>
      <webElementGuid>faa4dda6-c82a-4e89-8e2a-ba6971797270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only people you invite and moderators can see'])[1]/following::textarea[1]</value>
      <webElementGuid>3cdc98a7-091a-4a0d-83b3-f5567e690c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>880e2357-b4be-42fd-b754-9a71c3729b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughs here...' and (text() = 'hi' or . = 'hi')]</value>
      <webElementGuid>75d9ced8-863a-4c4d-a008-824a8ad51b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
