<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_h</name>
   <tag></tag>
   <elementGuidId>00d25542-d0d0-4734-9f91-bfdf43b1b34d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='editorReactMention'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>25b573f9-dee6-41ff-aea2-d43df82758e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editorReactMention</value>
      <webElementGuid>bef198f6-f51c-4b46-8109-79d5b91df9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your thoughs here...</value>
      <webElementGuid>729cfd39-56ef-4712-bb87-a34a021d84f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark:bg-channelTextarea__input</value>
      <webElementGuid>3a20dac3-8263-45d6-bacb-9c004f7e839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>h</value>
      <webElementGuid>5d2f189b-59e8-475a-becc-e60391b65be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-layout&quot;)/div[@class=&quot;flex h-screen text-gray-100 overflow-hidden relative dark:bg-bgPrimary bg-bgLightModeSecond&quot;]/div[@class=&quot;flex flex-row flex-1 bg-transparent&quot;]/div[@class=&quot;w-[480px] dark:bg-bgPrimary bg-bgLightModeSecond rounded-l-lg&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex flex-col flex-1 justify-end&quot;]/div[@class=&quot;flex-shrink-0 flex flex-col pb-4 px-4 dark:bg-bgPrimary bg-bgLightModeSecond h-auto relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;dark:bg-channelTextarea bg-channelTextareaLight dark:text-white text-colorTextLightMode rounded-md darkMode dark:bg-channelTextarea--multiLine&quot;]/div[@class=&quot;dark:bg-channelTextarea__control&quot;]/textarea[@id=&quot;editorReactMention&quot;]</value>
      <webElementGuid>c1eabb6f-54b7-44c3-bf6f-a4b64f189096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='editorReactMention'])[2]</value>
      <webElementGuid>6a593898-ebb4-4315-b745-213575d88bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-layout']/div/div[2]/div[4]/div/div[2]/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>e6382980-9e09-47bc-9b3e-94bde2af305b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='h'])[1]/following::textarea[1]</value>
      <webElementGuid>46e465a5-b38c-4cf5-aa8c-a54c01bccb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only people you invite and moderators can see'])[1]/following::textarea[1]</value>
      <webElementGuid>86a16ab6-60e1-4937-bcfb-742ef1b1bbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>2b3bff28-6b0d-42c8-ac88-c9a8925b28d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'editorReactMention' and @placeholder = 'Write your thoughs here...' and (text() = 'h' or . = 'h')]</value>
      <webElementGuid>52f63752-c4dc-406a-923c-46dea54304f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
